rdfa:
    - https://schema.org/version/latest/schema.rdf
    - https://schema.org/version/latest/ext-pending.rdf
id:
    generationStrategy: uuid
types:
    JobPosting:
        properties:
            title:
                nullable: false
            url: ~
            datePosted:
                range: Date
                nullable: false
            employerOverview:
                nullable: false
            employmentType:
                nullable: false
            experienceRequirements:
                nullable: false
            jobStartDate:
                range: Date
            skills:
                nullable: false
            validThrough:
                range: Date
            hiringOrganization: ~
    Organization:
        properties:
            name:
                nullable: false
            description: ~
            url:
                nullable: false
            email:
                nullable: false
            image:
                range: URL
            address:
                range: PostalAddress
            contactPoints: ~
            foundingDate: ~
    PostalAddress:
        properties:
            streetAddress: ~
            postalCode:
                nullable: false
            addressLocality:
                nullable: false
            addressCountry: ~
    ContactPoint:
        properties:
            name:
                nullable: false
            email:
                nullable: false
            telephone: ~
            contactType: ~
