id:
    generationStrategy: uuid
types:
    JobPosting:
        properties:
            title: ~
            url: ~
            datePosted: ~
            employerOverview:
                range: Text
            employmentType: ~
            experienceRequirements: ~
            jobStartDate:
                range: Date
            skills: ~
            validThrough: ~
            hiringOrganization: ~
    Organization:
        properties:
            name: ~
            description: ~
            url: ~
            email: ~
            image: ~
            address:
                range: PostalAddress
            contactPoints: ~
    PostalAddress:
        properties:
            streetAddress: ~
            postalCode: ~
            addressLocality: ~
            addressCountry: ~
    ContactPoint:
        properties:
            name: ~
            email: ~
            telephone: ~
            contactType: ~
